### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by Tom34772** [yungtry/CatalinaScrobbler#3] opened 2019-07-12 14:30 UTC
That’s *way* too much memory for it to be using, correct?

![Screen Shot 2019-07-12 at 10 22 42 AM](https://user-images.githubusercontent.com/52358827/61135633-0b19d900-a490-11e9-9003-036ad6476776.png)

Thank you for your work!
Tom

**Comment by yungtry** [comment] 2019-07-12 16:12
Thank you for reporting the issue. The memory leak is probably caused by loop updating data in the menu bar as there is no native way of updating it in electron (https://github.com/electron/electron/issues/10951#issuecomment-452809202). I'm going to implement this in other way than a loop. Meanwhile when I work on it, you can use the older version of application (1.0.2) without "graphical interface", which as I suppose did not have this kind of issue.

**Comment by yungtry** [comment] 2019-07-12 17:12
https://github.com/yungtry/CatalinaScrobbler/releases/tag/1.0.4 Let me know if it still occurs 😊.

**Comment by Tom34772** [comment] 2019-07-15 11:35
Both the 1.0.4 beta and 1.0.4 final version are still leaking memory. This morning, I watched CS go up probably a 3-4 MB every 5 seconds or so.

**Comment by yungtry** [comment] 2019-07-19 15:44
Happened to me for the first time today. I'm currently trying to figure out how to reproduce this. If anyone has any clues then I would be more than grateful if you could share them. For now it seems like something bugs out after few hours of listening to music causing the app to call few instances at the same time.

**Comment by yungtry** [comment] 2019-08-08 01:02
I'm going to close it for now since the app has been rewritten and the leak doesn't seem to be the case anymore. If anyone still encounters memory leaking, please mention me here I will reopen that issue.

**Closed as completed by yungtry** 2019-08-08 01:02 UTC
Labels: enhancement, help wanted
